use parallel_revm_lab_analyzer::{analyze_block_trace, ParallelismReport};
use parallel_revm_lab_trace_model::{
    Address as TraceAddress, BlockAccessTrace, BlockRef, ChainKind, StorageKey, TraceAccess,
    TraceAccessKey, TraceAccessKind, TracePack, TracePackAccess, TracePackAccessKind,
    TracePackBlock, TracePackError, TracePackManifest, TracePackTx, TraceParseWarning, TxHash,
    TxIndex, TxTrace, TRACE_PACK_SCHEMA_VERSION,
};
use revm::{
    context::TxEnv,
    database::{CacheDB, EmptyDB},
    interpreter::{
        interpreter_types::{InputsTr, Jumps, StackTr},
        Interpreter, InterpreterTypes,
    },
    primitives::{Address, Bytes, TxKind, U256},
    state::{bytecode::opcode, AccountInfo, Bytecode},
    Context, InspectEvm, Inspector, MainBuilder, MainContext,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BytecodeFixture {
    CounterSlot { slot: u8 },
    WriteSlot { slot: u8 },
    HotSlot { slot: u8 },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RevmSmokeTx {
    pub tx_index: u64,
    pub caller: Address,
    pub contract: Address,
    pub fixture: BytecodeFixture,
}

pub fn smoke_report(txs: &[RevmSmokeTx]) -> Result<ParallelismReport, RevmSmokeError> {
    Ok(analyze_block_trace(&smoke_trace(txs)?, false, false))
}

pub fn smoke_trace_pack(txs: &[RevmSmokeTx]) -> Result<TracePack, RevmSmokeError> {
    let trace = smoke_trace(txs)?;
    let mut pack = TracePack {
        manifest: TracePackManifest {
            schema_version: TRACE_PACK_SCHEMA_VERSION.to_owned(),
            chain: ChainKind::new("revm-smoke"),
            source: "revm-smoke-inspector".to_owned(),
            provenance: "real revm bytecode execution over tiny in-memory fixtures".to_owned(),
            start_block: trace.block.number,
            end_block: trace.block.number,
            created_by_tool_version: env!("CARGO_PKG_VERSION").to_owned(),
            tracer_kind: "revm-inspector-sload-sstore".to_owned(),
            notes: vec!["Generated by crates/revm-smoke from in-process revm execution".to_owned()],
            warnings: vec![
                "Storage opcode observations only; account/code/balance reads are not represented"
                    .to_owned(),
            ],
        },
        blocks: vec![trace_to_pack_block(&trace)],
    };
    pack.normalize();
    pack.validate()?;
    Ok(pack)
}

pub fn smoke_trace(txs: &[RevmSmokeTx]) -> Result<BlockAccessTrace, RevmSmokeError> {
    let mut traces = Vec::with_capacity(txs.len());
    for tx in txs {
        let accesses = execute_fixture(tx)?;
        traces.push(tx_trace(tx, accesses));
    }

    let mut trace = BlockAccessTrace {
        chain: ChainKind::new("revm-smoke"),
        block: BlockRef {
            number: 0,
            hash: None,
        },
        transactions: traces,
        warnings: vec![TraceParseWarning {
            tx_index: None,
            message: "revm smoke inspector records SLOAD/SSTORE storage access only; account, balance, nonce, and code reads are not represented".to_owned(),
        }],
    };
    trace.normalize();
    trace.validate()?;
    Ok(trace)
}

fn trace_to_pack_block(trace: &BlockAccessTrace) -> TracePackBlock {
    TracePackBlock {
        chain: trace.chain.clone(),
        block_number: trace.block.number,
        block_hash: trace.block.hash.clone(),
        parent_hash: None,
        tx_count: trace.transactions.len(),
        total_gas_used: None,
        transactions: trace.transactions.iter().map(trace_tx_to_pack_tx).collect(),
        warnings: trace
            .warnings
            .iter()
            .map(|warning| warning.message.clone())
            .collect(),
    }
}

fn trace_tx_to_pack_tx(tx: &TxTrace) -> TracePackTx {
    TracePackTx {
        tx_index: tx.tx_index,
        tx_hash: tx.tx_hash.clone(),
        from: Some(tx.from.clone()),
        to: tx.to.clone(),
        gas_used: None,
        status: Some("success".to_owned()),
        accesses: tx
            .accesses
            .iter()
            .map(|access| {
                let (address, slot) = match &access.key {
                    TraceAccessKey::Storage { address, slot } => {
                        (address.clone(), Some(slot.clone()))
                    }
                    key => (key.address().clone(), None),
                };
                TracePackAccess {
                    address,
                    slot,
                    kind: match access.kind {
                        TraceAccessKind::Read => TracePackAccessKind::Read,
                        TraceAccessKind::Write => TracePackAccessKind::Write,
                        TraceAccessKind::ReadWrite => TracePackAccessKind::ReadWrite,
                    },
                    op: Some(
                        match access.kind {
                            TraceAccessKind::Read => "SLOAD",
                            TraceAccessKind::Write | TraceAccessKind::ReadWrite => "SSTORE",
                        }
                        .to_owned(),
                    ),
                    pc: None,
                    depth: None,
                    gas_remaining: None,
                }
            })
            .collect(),
        warnings: tx
            .warnings
            .iter()
            .map(|warning| warning.message.clone())
            .collect(),
    }
}

fn execute_fixture(tx: &RevmSmokeTx) -> Result<Vec<ObservedStorageAccess>, RevmSmokeError> {
    let mut db = CacheDB::<EmptyDB>::default();
    db.insert_account_info(
        tx.caller,
        AccountInfo {
            balance: U256::from(1_000_000_000_000_000_u64),
            ..AccountInfo::default()
        },
    );
    db.insert_account_info(
        tx.contract,
        AccountInfo::default().with_code(Bytecode::new_raw(bytecode(tx.fixture))),
    );
    db.insert_account_storage(tx.contract, U256::from(slot(tx.fixture)), U256::ZERO)
        .map_err(|_| RevmSmokeError::StorageSeed)?;

    let ctx = Context::mainnet().with_db(db);
    let mut evm = ctx.build_mainnet_with_inspector(StorageAccessInspector::default());
    let tx_env = TxEnv::builder()
        .caller(tx.caller)
        .kind(TxKind::Call(tx.contract))
        .gas_limit(100_000)
        .build()
        .map_err(|err| RevmSmokeError::BuildTx(err.to_string()))?;
    let result = evm
        .inspect_tx(tx_env)
        .map_err(|err| RevmSmokeError::Execution(err.to_string()))?;
    if result.result.is_success() {
        Ok(evm.inspector.accesses)
    } else {
        Err(RevmSmokeError::Unsuccessful(format!("{:?}", result.result)))
    }
}

fn tx_trace(tx: &RevmSmokeTx, observed: Vec<ObservedStorageAccess>) -> TxTrace {
    TxTrace {
        tx_index: TxIndex(tx.tx_index),
        tx_hash: TxHash(format!("0x{:064x}", tx.tx_index)),
        from: trace_address(tx.caller),
        to: Some(trace_address(tx.contract)),
        read_info_complete: false,
        accesses: observed
            .into_iter()
            .map(|access| TraceAccess {
                kind: access.kind,
                key: TraceAccessKey::Storage {
                    address: trace_address(access.contract),
                    slot: u256_storage_key(access.slot),
                },
            })
            .collect(),
        warnings: vec![TraceParseWarning {
            tx_index: Some(TxIndex(tx.tx_index)),
            message: "revm smoke inspector marks reads incomplete outside SLOAD".to_owned(),
        }],
    }
}

#[derive(Clone, Debug)]
struct ObservedStorageAccess {
    contract: Address,
    slot: U256,
    kind: TraceAccessKind,
}

#[derive(Default, Debug)]
struct StorageAccessInspector {
    accesses: Vec<ObservedStorageAccess>,
}

impl<CTX, INTR> Inspector<CTX, INTR> for StorageAccessInspector
where
    INTR: InterpreterTypes,
    INTR::Bytecode: Jumps,
    INTR::Stack: StackTr,
    INTR::Input: InputsTr,
{
    fn step(&mut self, interp: &mut Interpreter<INTR>, _context: &mut CTX) {
        let kind = match interp.bytecode.opcode() {
            opcode::SLOAD => TraceAccessKind::Read,
            opcode::SSTORE => TraceAccessKind::Write,
            _ => return,
        };
        let Some(slot) = interp.stack.data().last().copied() else {
            return;
        };
        self.accesses.push(ObservedStorageAccess {
            contract: interp.input.target_address(),
            slot,
            kind,
        });
    }
}

fn bytecode(fixture: BytecodeFixture) -> Bytes {
    match fixture {
        BytecodeFixture::CounterSlot { slot } | BytecodeFixture::HotSlot { slot } => {
            Bytes::from(vec![
                0x60, slot, 0x54, 0x60, 0x01, 0x01, 0x60, slot, 0x55, 0x00,
            ])
        }
        BytecodeFixture::WriteSlot { slot } => {
            Bytes::from(vec![0x60, 0x01, 0x60, slot, 0x55, 0x00])
        }
    }
}

fn slot(fixture: BytecodeFixture) -> u8 {
    match fixture {
        BytecodeFixture::CounterSlot { slot }
        | BytecodeFixture::WriteSlot { slot }
        | BytecodeFixture::HotSlot { slot } => slot,
    }
}

fn trace_address(address: Address) -> TraceAddress {
    TraceAddress::canonical(address.to_string())
}

fn u256_storage_key(value: U256) -> StorageKey {
    StorageKey::canonical(format!("0x{value:064x}"))
}

#[derive(Debug, thiserror::Error)]
pub enum RevmSmokeError {
    #[error("failed to build revm tx env: {0}")]
    BuildTx(String),
    #[error("failed to seed revm storage")]
    StorageSeed,
    #[error("revm execution failed: {0}")]
    Execution(String),
    #[error("revm execution was not successful: {0}")]
    Unsuccessful(String),
    #[error(transparent)]
    TraceModel(#[from] parallel_revm_lab_trace_model::TraceModelError),
    #[error(transparent)]
    TracePack(#[from] TracePackError),
}

#[cfg(test)]
mod tests {
    use super::*;

    const CONTRACT: Address = Address::new([0x22; 20]);

    #[test]
    fn revm_counter_txs_conflict_on_same_slot() {
        let txs = vec![
            tx(0, 0x10, BytecodeFixture::CounterSlot { slot: 0 }),
            tx(1, 0x11, BytecodeFixture::CounterSlot { slot: 0 }),
        ];
        let report = smoke_report(&txs).unwrap();

        assert_eq!(report.conflict_pair_count, 1);
        assert_eq!(report.wave_count, 2);
        assert_eq!(report.critical_path_length, 2);
    }

    #[test]
    fn revm_independent_slot_txs_can_share_wave() {
        let txs = vec![
            tx(0, 0x10, BytecodeFixture::WriteSlot { slot: 1 }),
            tx(1, 0x11, BytecodeFixture::WriteSlot { slot: 2 }),
            tx(2, 0x12, BytecodeFixture::WriteSlot { slot: 3 }),
        ];
        let report = smoke_report(&txs).unwrap();

        assert_eq!(report.conflict_pair_count, 0);
        assert_eq!(report.wave_count, 1);
        assert_eq!(report.max_wave_width, 3);
    }

    #[test]
    fn revm_smoke_report_is_deterministic() {
        let txs = vec![
            tx(0, 0x10, BytecodeFixture::HotSlot { slot: 7 }),
            tx(1, 0x11, BytecodeFixture::WriteSlot { slot: 8 }),
            tx(2, 0x12, BytecodeFixture::HotSlot { slot: 7 }),
        ];

        let left = smoke_report(&txs).unwrap();
        let right = smoke_report(&txs).unwrap();
        assert_eq!(left.deterministic_hash, right.deterministic_hash);
        assert_eq!(left.conflict_pair_count, 1);
        assert_eq!(left.wave_count, 2);
    }

    #[test]
    fn revm_smoke_trace_pack_validates_and_analyzes() {
        let txs = vec![
            tx(0, 0x10, BytecodeFixture::HotSlot { slot: 7 }),
            tx(1, 0x11, BytecodeFixture::WriteSlot { slot: 8 }),
            tx(2, 0x12, BytecodeFixture::HotSlot { slot: 7 }),
        ];
        let pack = smoke_trace_pack(&txs).unwrap();
        let dossier = parallel_revm_lab_analyzer::analyze_trace_pack(&pack, &[1, 2, 4]);

        assert_eq!(pack.blocks.len(), 1);
        assert_eq!(dossier.tx_count, 3);
        assert_eq!(dossier.conflict_pair_count, 1);
        assert!(dossier.gas_weighted_critical_path.is_none());
    }

    fn tx(tx_index: u64, caller_byte: u8, fixture: BytecodeFixture) -> RevmSmokeTx {
        RevmSmokeTx {
            tx_index,
            caller: Address::new([caller_byte; 20]),
            contract: CONTRACT,
            fixture,
        }
    }
}
